<a href="https://colab.research.google.com/github/pmy0792/pytorch_tutorial/blob/main/lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

### **1D Array with Numpy**

In [2]:
t=np.array([0.,1.,2.,3.,4.,5.,6.,])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t:',t.ndim)
print('Shape of t:',t.shape)

Rank of t: 1
Shape of t: (7,)


In [5]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])
print('t[2:5] t[4:-1]  = ',t[2:5], t[4:-1])
print('t[:2] t[3:]     = ',t[:2],t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### **2D Array with Numpy**

In [6]:
t=np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('Rank of t:',t.ndim)
print('Shape of t:',t.shape)

Rank of t: 2
Shape of t: (4, 3)


### **1D Array with PyTorch**

In [8]:
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### **2D Array with PyTorch**

In [10]:
t=torch.FloatTensor([[1.,2.,3.],
                     [4.,5.,6.],
                     [7.,8.,9.],
                     [10.,11.,12.]
                     ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print(t.dim()) #rank
print(t.size()) #shape
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### **Broadcasting**

In [12]:
# same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [13]:
# Vector + scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3]]) # 3-> [[3,3]]
print(m1+m2) # [[1,2]] + [[3,3]]

tensor([[4., 5.]])


In [14]:
# 2 x 1 Vector + 1 x 2 Vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### **Multiplication vs Matrix Multiplication**

> Indented block



In [18]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of m1: ',m1.shape)
print('Shape of m2: ',m2.shape)
print(m1.matmul(m2)) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))



-------------
Mul vs Matmul
-------------
Shape of m1:  torch.Size([2, 2])
Shape of m2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### **Mean**

In [19]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [20]:
# Can't use mean() on integers
t=torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [23]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### **Sum**

In [25]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### **Max and Argmax**

In [27]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.max())

tensor(4.)


In [29]:
print(t.max(dim=0)) #dimension 0 이 없어진다
print('Max: ',t.max(dim=0)[0])
print('Argmax: ',t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [30]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### **View(Reshape)** 

In [32]:
t=np.array([[[0,1,2],
            [3,4,5]],
           
           [[6,7,8],
            [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [33]:
print(ft.view([-1,3])) # [2,2,3] -> [2*2, 3]
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [34]:
print(ft.view([-1,1,3])) # [2,2,3] -> [2*2, 1, 3]
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### **Squeeze** 

In [36]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [38]:
print(ft.squeeze()) # 값이 1인 dim이 날라감
print(ft.squeeze(dim=1))
print(ft.squeeze().shape)

tensor([0., 1., 2.])
tensor([0., 1., 2.])
torch.Size([3])


### **Unsqueeze** 

In [39]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [40]:
print(ft.unsqueeze(0)) # 0번째 dim에 1을 넣는다
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [42]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [44]:
print(ft.unsqueeze(-1)) #마지막 dim이 1이 된다
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### **TypeCasting** 

In [45]:
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [46]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [47]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [48]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### **Concatenate** 

In [49]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [50]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### **Stacking** 

In [51]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [52]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [53]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### **Ones and Zeros** 

In [54]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [55]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### **In-place Operation** 

In [56]:
x=torch.FloatTensor([[1,2],[3,4]])

In [57]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
